### ISSUE TITLE
quick styles are not contained to one viewer

### ISSUE THREAD

**Issue by jmbuhr** [jmbuhr/quarto-molstar#10]
Looks like with the addition of the example snapshot, which uses a quick style "Stylized", all other apps in the document use this style on startup as well. Changing the style in one app changes it for the other apps as well, as soon as they are hovered afterwards.

Is this a bug or a feature?

**Comment by jmbuhr** [comment]
It is also not the same for different styles. Switching between default and stylized has a global behavior, but "illustrative" only makes other viewers stylized. Very peculiar indeed.

**Comment by BradyAJohnston** [comment]
It seems that it's not the entirety of the style, but just the outline that is now applied to all of the viewers. I've had a bit of a poke around but don't really know enough javascript to try and figure out what is going on.

**Comment by jmbuhr** [comment]
So far I found it for `Occlusion` and `Outline` but nothing else indeed.
![image](https://user-images.githubusercontent.com/17450586/186187674-a89125eb-afb3-41b8-9ebd-e567c36fc3af.png)

**Comment by BradyAJohnston** [comment]
Seems that you can then change these options in one viewer, without it changing in the other viewers. For some reason only in the setup the outline / occlusion is being picked up from the one viewer and applied to the others. Very interesting...

**Comment by BradyAJohnston** [comment]
Actually scratch that. If you change it it one viewer, it changes the other viewers as well. They won't update until you mouse-over them, but changing the occlusion & outline in one changes it in the others too. This seems like it is an issue worth reporting to the devs?
